cos_epochs: 300
d_model: 256
dec_activation: relu
dec_d_ff: 1024
dec_max_num_hops: 2
dec_n_head: 8
dec_nc: 3
dec_np: 3
dropout: 0.3
edge_emb_size: 256
edge_vocab_size: 7
enc_block_config: 16
enc_d_in: 684
enc_growth_rate: 24
enc_in_channels: 1
label_smoothing: 0
labmda_p: 1
lambda_e: 1
lambda_v: 1
lambda_vp: 0.1
lr: 0.0003
node_emb_size: 256
node_vocab_size: 107
optim: adamw
pad_idx: 0
restart: hard
warmup: 20
